name: "Create Artifact From Synth"

inputs:
  stage_name:
    required: true
    type: string
  account:
    required: true
    type: string
  region:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Synth Artifact
      env:
        ACCOUNT: ${{inputs.account}}
        REGION: ${{inputs.region}}
      shell: bash
      run: |
        npm run cdk synth -- --context stage=${{inputs.stage_name}} \
        --quiet \
        --output build/${{inputs.stage_name}}/cdk.out

    - name: Upload Synth As Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{inputs.stage_name}}-artifact
        path: build/${{inputs.stage_name}}/cdk.out
